name: Push Event

on: push

jobs:
  run-client-push:
    runs-on: ubuntu-latest
    environment: test
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: sleep
      run: sleep 60
    
    - name: Run client_push script      
      run: python3 client.py "${{ secrets.SERVER_IP }}" ${{ secrets.SERVER_PORT }} "push action" ${{ secrets.TEST_KEY }}
    
    - name: run test
      run: echo "888"
      # run: echo "SERVER_TEST="

    - name: Print environment variables
      env:
          SERVER_TEST: ${{ secrets.TEST_KEY }}
      run: echo "SERVER_TEST=$TEST_KEY"
