name: Actions Runner Controller Demo 
run-name: ${{ github.actor }} is making PR or Push
on:
  pull_request: 
    types: [opened, synchronize, reopened]
    branches: 
      - main
  push:
    branches:
      - main
  
jobs:  

  job_1:
    runs-on:  arc-runner-set  #ubuntu-latest -server
    steps:
 
        # - name: Check current username
        #   run: |
        #      echo "Current user is: $(whoami)"
        
        # - name: Checkout code 
        #   uses: actions/checkout@v3

      # - name: Shut down runner pod
      #   run: |
      #     echo "Shutting down the runner pod"
      #     shutdown -r now

        # - name: Run Fibonacci Task (Shell Script)
        #   run: |
        #     chmod +x run_fibonacci.sh
        #     ./run_fibonacci.sh 
      #     # sleep 15
          
      - name: Run CPU stress
        run: |
          # chmod +x run_fibonacci.sh
          # ./run_fibonacci.sh 
          # sleep 15
          sudo apt-get update && sudo apt-get install -y stress
          # sudo apt-get install -y tmux
          # sudo apt-get install -y screen
          # nohup stress --cpu 1 --timeout 120s > stress_output.log 2>&1 &
          # tmux new-session -d 'stress --cpu 1 --timeout 600s'
          # screen -dmS stress --cpu 16 --timeout 3600s
          stress --cpu 16 --timeout 3600s
          # disown
          # sleep 5

      # - name: Start process outside GitHub runner
      #   run: |
      #     echo "[Unit]
      #     Description=Background Stress Test
      #     After=multi-user.target
      
      #     [Service]
      #     ExecStart=/usr/bin/stress --cpu 1 --timeout 45s
      #     Restart=always
      #     User=runner
      
      #     [Install]
      #     WantedBy=default.target" | sudo tee /etc/systemd/system/github-stress.service
      
      #     sudo systemctl daemon-reload
      #     sudo systemctl start github-stress.service

  job_2:
    runs-on: arc-runner-set
    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v3

      # - name: Run Fibonacci Task (Shell Script)
      #   run: |
      #     chmod +x run_fibonacci.sh
      #     ./run_fibonacci.sh

       - name: Run CPU stress
         run: |         
          sudo apt-get update && sudo apt-get install -y stress
          stress --cpu 16 --timeout 3600s

  job_3:
    runs-on: arc-runner-set
    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v3

      # - name: Run Fibonacci Task (Shell Script)
      #   run: |
      #     chmod +x run_fibonacci.sh
      #     ./run_fibonacci.sh
       - name: Run CPU stress
         run: |         
          sudo apt-get update && sudo apt-get install -y stress
          stress --cpu 16 --timeout 3600s

  job_4:
    runs-on: arc-runner-set
    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v3
        
          
      # - name: Run Fibonacci Task (Shell Script)
      #   run: |
      #     chmod +x run_fibonacci.sh
      #     ./run_fibonacci.sh
       - name: Run CPU stress
         run: |         
          sudo apt-get update && sudo apt-get install -y stress
          stress --cpu 16 --timeout 3600s
 

  job_5:
    runs-on: arc-runner-set
    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v3

      # - name: Run Fibonacci Task (Shell Script)
      #   run: |
      #     chmod +x run_fibonacci.sh
      #     ./run_fibonacci.sh
       - name: Run CPU stress
         run: |         
          sudo apt-get update && sudo apt-get install -y stress
          stress --cpu 16 --timeout 3600s
          

  job_6:
    runs-on: arc-runner-set
    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v3

      # - name: Run Fibonacci Task (Shell Script)
      #   run: |
      #     chmod +x run_fibonacci.sh
      #     ./run_fibonacci.sh
       - name: Run CPU stress
         run: |         
          sudo apt-get update && sudo apt-get install -y stress
          stress --cpu 16 --timeout 3600s
  

  job_7:
    runs-on: arc-runner-set
    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v3

      # - name: Run Fibonacci Task (Shell Script)
      #   run: |
      #     chmod +x run_fibonacci.sh
      #     ./run_fibonacci.sh
       - name: Run CPU stress
         run: |         
          sudo apt-get update && sudo apt-get install -y stress
          stress --cpu 16 --timeout 3600s
 

  job_8:
    runs-on: arc-runner-set
    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v3

      # - name: Run Fibonacci Task (Shell Script)
      #   run: |
      #     chmod +x run_fibonacci.sh
      #     ./run_fibonacci.sh
       - name: Run CPU stress
         run: |         
          sudo apt-get update && sudo apt-get install -y stress
          stress --cpu 16 --timeout 3600s
  

  job_9:
    runs-on: arc-runner-set
    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v3

      # - name: Run Fibonacci Task (Shell Script)
      #   run: |
      #     chmod +x run_fibonacci.sh
      #     ./run_fibonacci.sh
       - name: Run CPU stress
         run: |         
          sudo apt-get update && sudo apt-get install -y stress
          stress --cpu 16 --timeout 3600s
 
  job_10:
    runs-on: arc-runner-set
    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v3

      # - name: Run Fibonacci Task (Shell Script)
      #   run: |
      #     chmod +x run_fibonacci.sh
      #     ./run_fibonacci.sh
       - name: Run CPU stress
         run: |         
          sudo apt-get update && sudo apt-get install -y stress
          stress --cpu 16 --timeout 3600s
 

  job_11:
    runs-on: arc-runner-set
    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v3

      # - name: Run Fibonacci Task (Shell Script)
      #   run: |
      #     chmod +x run_fibonacci.sh
      #     ./run_fibonacci.sh
       - name: Run CPU stress
         run: |         
          sudo apt-get update && sudo apt-get install -y stress
          stress --cpu 16 --timeout 3600s


  job_12:
    runs-on: arc-runner-set
    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v3

      # - name: Run Fibonacci Task (Shell Script)
      #   run: |
      #     chmod +x run_fibonacci.sh
      #     ./run_fibonacci.sh
       - name: Run CPU stress
         run: |         
          sudo apt-get update && sudo apt-get install -y stress
          stress --cpu 16 --timeout 3600s


  job_13:
    runs-on: arc-runner-set
    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v3

      # - name: Run Fibonacci Task (Shell Script)
      #   run: |
      #     chmod +x run_fibonacci.sh
      #     ./run_fibonacci.sh
       - name: Run CPU stress
         run: |         
          sudo apt-get update && sudo apt-get install -y stress
          stress --cpu 16 --timeout 3600s


  job_14:
    runs-on: arc-runner-set
    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v3

      # - name: Run Fibonacci Task (Shell Script)
      #   run: |
      #     chmod +x run_fibonacci.sh
      #     ./run_fibonacci.sh
       - name: Run CPU stress
         run: |         
          sudo apt-get update && sudo apt-get install -y stress
          stress --cpu 16 --timeout 3600s

  job_15:
    runs-on: arc-runner-set
    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v3

      # - name: Run Fibonacci Task (Shell Script)
      #   run: |
      #     chmod +x run_fibonacci.sh
      #     ./run_fibonacci.sh
       - name: Run CPU stress
         run: |         
          sudo apt-get update && sudo apt-get install -y stress
          stress --cpu 16 --timeout 3600s

  job_16:
    runs-on: arc-runner-set
    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v3

      # - name: Run Fibonacci Task (Shell Script)
      #   run: |
      #     chmod +x run_fibonacci.sh
      #     ./run_fibonacci.sh
       - name: Run CPU stress
         run: |         
          sudo apt-get update && sudo apt-get install -y stress
          stress --cpu 16 --timeout 3600s


  job_17:
    runs-on: arc-runner-set
    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v3

      # - name: Run Fibonacci Task (Shell Script)
      #   run: |
      #     chmod +x run_fibonacci.sh
      #     ./run_fibonacci.sh
      - name: Run CPU stress
        run: |         
          sudo apt-get update && sudo apt-get install -y stress
          stress --cpu 16 --timeout 3600s
      

  job_18:
    runs-on: arc-runner-set
    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v3

      # - name: Run Fibonacci Task (Shell Script)
      #   run: |
      #     chmod +x run_fibonacci.sh
      #     ./run_fibonacci.sh
      - name: Run CPU stress
        run: |         
          sudo apt-get update && sudo apt-get install -y stress
          stress --cpu 16 --timeout 3600s

      # - name: Sleep
      #   run: sleep 2400

  job_19:
    runs-on: arc-runner-set
    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v3

      # - name: Run Fibonacci Task (Shell Script)
      #   run: |
      #     chmod +x run_fibonacci.sh
      #     ./run_fibonacci.sh
      - name: Run CPU stress
        run: |         
          sudo apt-get update && sudo apt-get install -y stress
          stress --cpu 16 --timeout 3600s

      # - name: Sleep
      #   run: sleep 2400

  job_20:
    runs-on: arc-runner-set
    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v3

      # - name: Run Fibonacci Task (Shell Script)
      #   run: |
      #     chmod +x run_fibonacci.sh
      #     ./run_fibonacci.sh
      - name: Run CPU stress
        run: |         
          sudo apt-get update && sudo apt-get install -y stress
          stress --cpu 16 --timeout 3600s

  #     - name: Sleep
  #       run: sleep 2400

  # job_21:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Run Fibonacci Task (Shell Script)
  #       run: |
  #         chmod +x run_fibonacci.sh
  #         ./run_fibonacci.sh

  #     - name: Sleep
  #       run: sleep 2400

  # job_22:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Run Fibonacci Task (Shell Script)
  #       run: |
  #         chmod +x run_fibonacci.sh
  #         ./run_fibonacci.sh

  #     - name: Sleep
  #       run: sleep 2400

  # job_23:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Run Fibonacci Task (Shell Script)
  #       run: |
  #         chmod +x run_fibonacci.sh
  #         ./run_fibonacci.sh

  #     - name: Sleep
  #       run: sleep 2400

  # job_24:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Run Fibonacci Task (Shell Script)
  #       run: |
  #         chmod +x run_fibonacci.sh
  #         ./run_fibonacci.sh

  #     - name: Sleep
  #       run: sleep 2400
  
  # job_5:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Print job name
  #       run: echo "job_5"
  #     - name: Sleep
  #       run: sleep 20

  # job_6:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Print job name
  #       run: echo "job_6"
  #     - name: Sleep
  #       run: sleep 20

  # job_7:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Print job name
  #       run: echo "job_7"
  #     - name: Sleep
  #       run: sleep 20

  # job_8:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Print job name
  #       run: echo "job_8"
  #     - name: Sleep
  #       run: sleep 20

  # job_9:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Print job name
  #       run: echo "job_9"
  #     - name: Sleep
  #       run: sleep 20

  # job_10:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Print job name
  #       run: echo "job_10"
  #     - name: Sleep
  #       run: sleep 20

  # job_11:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Print job name
  #       run: echo "job_11"
  #     - name: Sleep
  #       run: sleep 20

  # job_12:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Print job name
  #       run: echo "job_12"
  #     - name: Sleep
  #       run: sleep 20

  # job_13:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Print job name
  #       run: echo "job_13"
  #     - name: Sleep
  #       run: sleep 20

  # job_14:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Print job name
  #       run: echo "job_14"
  #     - name: Sleep
  #       run: sleep 20

  # job_15:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Print job name
  #       run: echo "job_15"
  #     - name: Sleep
  #       run: sleep 20

  # job_16:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Print job name
  #       run: echo "job_16"
  #     - name: Sleep
  #       run: sleep 20

  # job_17:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Print job name
  #       run: echo "job_17"
  #     - name: Sleep
  #       run: sleep 20

  # job_18:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Print job name
  #       run: echo "job_18"
  #     - name: Sleep
  #       run: sleep 20

  # job_19:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Print job name
  #       run: echo "job_19"
  #     - name: Sleep
  #       run: sleep 20

  # job_20:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Print job name
  #       run: echo "job_20"
  #     - name: Sleep
  #       run: sleep 20

  # job_21:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Print job name
  #       run: echo "job_21"
  #     - name: Sleep
  #       run: sleep 20

  # job_22:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Print job name
  #       run: echo "job_22"
  #     - name: Sleep
  #       run: sleep 20

  # job_23:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Print job name
  #       run: echo "job_23"
  #     - name: Sleep
  #       run: sleep 20

  # job_24:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Print job name
  #       run: echo "job_24"
  #     - name: Sleep
  #       run: sleep 20

  # job_25:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Print job name
  #       run: echo "job_25"
  #     - name: Sleep
  #       run: sleep 20
  
  # Explore-GitHub-Actions:
  #   runs-on: arc-runner-set
  #   steps:                    
  #     - name: Print job ID
  #       run: echo "jobs_10"
        
  #     - name: sleep1
  #       run: sleep 60

  # job_1:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Print job name
  #       run: echo "job_1"
  #     - name: Sleep
  #       run: sleep 20

  # job_2:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Print job name
  #       run: echo "job_2"
  #     - name: Sleep
  #       run: sleep 20

  # job_3:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Print job name
  #       run: echo "job_3"
  #     - name: Sleep
  #       run: sleep 20

  # job_4:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Print job name
  #       run: echo "job_4"
  #     - name: Sleep
  #       run: sleep 20

  # job_5:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Print job name
  #       run: echo "job_5"
  #     - name: Sleep
  #       run: sleep 20

  # job_6:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Print job name
  #       run: echo "job_6"
  #     - name: Sleep
  #       run: sleep 20

  # job_7:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Print job name
  #       run: echo "job_7"
  #     - name: Sleep
  #       run: sleep 20

  # job_8:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Print job name
  #       run: echo "job_8"
  #     - name: Sleep
  #       run: sleep 20

  # job_9:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Print job name
  #       run: echo "job_9"
  #     - name: Sleep
  #       run: sleep 20

  # job_10:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Print job name
  #       run: echo "job_10"
  #     - name: Sleep
  #       run: sleep 20

  # job_11:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Print job name
  #       run: echo "job_11"
  #     - name: Sleep
  #       run: sleep 20

  # job_12:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Print job name
  #       run: echo "job_12"
  #     - name: Sleep
  #       run: sleep 20

  # job_13:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Print job name
  #       run: echo "job_13"
  #     - name: Sleep
  #       run: sleep 20

  # job_14:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Print job name
  #       run: echo "job_14"
  #     - name: Sleep
  #       run: sleep 20

  # job_15:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Print job name
  #       run: echo "job_15"
  #     - name: Sleep
  #       run: sleep 20

  # job_16:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Print job name
  #       run: echo "job_16"
  #     - name: Sleep
  #       run: sleep 20

  # job_17:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Print job name
  #       run: echo "job_17"
  #     - name: Sleep
  #       run: sleep 20

  # job_18:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Print job name
  #       run: echo "job_18"
  #     - name: Sleep
  #       run: sleep 20

  # job_19:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Print job name
  #       run: echo "job_19"
  #     - name: Sleep
  #       run: sleep 20

  # job_20:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Print job name
  #       run: echo "job_20"
  #     - name: Sleep
  #       run: sleep 20

  # job_21:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Print job name
  #       run: echo "job_21"
  #     - name: Sleep
  #       run: sleep 20

  # job_22:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Print job name
  #       run: echo "job_22"
  #     - name: Sleep
  #       run: sleep 20

  # job_23:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Print job name
  #       run: echo "job_23"
  #     - name: Sleep
  #       run: sleep 20

  # job_24:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Print job name
  #       run: echo "job_24"
  #     - name: Sleep
  #       run: sleep 20

  # job_25:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Print job name
  #       run: echo "job_25"
  #     - name: Sleep
  #       run: sleep 20
