name: Actions Runner Controller Demo
run-name: ${{ github.actor }} is making PR or Push
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

jobs:

  job_1:
    runs-on: arc-runner-set #ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # - name: Shut down runner pod
      #   run: |
      #     echo "Shutting down the runner pod"
      #     shutdown -r now

      - name: Run Fibonacci Task (Shell Script)
        run: |
          chmod +x run_fibonacci.sh
          ./run_fibonacci.sh

  # job_2:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Run Fibonacci Task (Shell Script)
  #       run: |
  #         chmod +x run_fibonacci.sh
  #         ./run_fibonacci.sh

  # job_3:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Run Fibonacci Task (Shell Script)
  #       run: |
  #         chmod +x run_fibonacci.sh
  #         ./run_fibonacci.sh

  # job_4:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3
        
          
  #     - name: Run Fibonacci Task (Shell Script)
  #       run: |
  #         chmod +x run_fibonacci.sh
  #         ./run_fibonacci.sh
 

  # job_5:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Run Fibonacci Task (Shell Script)
  #       run: |
  #         chmod +x run_fibonacci.sh
  #         ./run_fibonacci.sh

  # job_6:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Run Fibonacci Task (Shell Script)
  #       run: |
  #         chmod +x run_fibonacci.sh
  #         ./run_fibonacci.sh
  

  # job_7:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Run Fibonacci Task (Shell Script)
  #       run: |
  #         chmod +x run_fibonacci.sh
  #         ./run_fibonacci.sh
 

  # job_8:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Run Fibonacci Task (Shell Script)
  #       run: |
  #         chmod +x run_fibonacci.sh
  #         ./run_fibonacci.sh
  

  # job_9:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Run Fibonacci Task (Shell Script)
  #       run: |
  #         chmod +x run_fibonacci.sh
  #         ./run_fibonacci.sh
 
  # job_10:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Run Fibonacci Task (Shell Script)
  #       run: |
  #         chmod +x run_fibonacci.sh
  #         ./run_fibonacci.sh
 

  # job_11:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Run Fibonacci Task (Shell Script)
  #       run: |
  #         chmod +x run_fibonacci.sh
  #         ./run_fibonacci.sh


  # job_12:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Run Fibonacci Task (Shell Script)
  #       run: |
  #         chmod +x run_fibonacci.sh
  #         ./run_fibonacci.sh

  #     - name: Sleep
  #       run: sleep 2400

  # job_13:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Run Fibonacci Task (Shell Script)
  #       run: |
  #         chmod +x run_fibonacci.sh
  #         ./run_fibonacci.sh

  #     - name: Sleep
  #       run: sleep 2400

  # job_14:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Run Fibonacci Task (Shell Script)
  #       run: |
  #         chmod +x run_fibonacci.sh
  #         ./run_fibonacci.sh

  #     - name: Sleep
  #       run: sleep 2400

  # job_15:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Run Fibonacci Task (Shell Script)
  #       run: |
  #         chmod +x run_fibonacci.sh
  #         ./run_fibonacci.sh

  #     - name: Sleep
  #       run: sleep 2400

  # job_16:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Run Fibonacci Task (Shell Script)
  #       run: |
  #         chmod +x run_fibonacci.sh
  #         ./run_fibonacci.sh

  #     - name: Sleep
  #       run: sleep 2400

  # job_17:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Run Fibonacci Task (Shell Script)
  #       run: |
  #         chmod +x run_fibonacci.sh
  #         ./run_fibonacci.sh

  #     - name: Sleep
  #       run: sleep 2400

  # job_18:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Run Fibonacci Task (Shell Script)
  #       run: |
  #         chmod +x run_fibonacci.sh
  #         ./run_fibonacci.sh

  #     - name: Sleep
  #       run: sleep 2400

  # job_19:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Run Fibonacci Task (Shell Script)
  #       run: |
  #         chmod +x run_fibonacci.sh
  #         ./run_fibonacci.sh

  #     - name: Sleep
  #       run: sleep 2400

  # job_20:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Run Fibonacci Task (Shell Script)
  #       run: |
  #         chmod +x run_fibonacci.sh
  #         ./run_fibonacci.sh

  #     - name: Sleep
  #       run: sleep 2400

  # job_21:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Run Fibonacci Task (Shell Script)
  #       run: |
  #         chmod +x run_fibonacci.sh
  #         ./run_fibonacci.sh

  #     - name: Sleep
  #       run: sleep 2400

  # job_22:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Run Fibonacci Task (Shell Script)
  #       run: |
  #         chmod +x run_fibonacci.sh
  #         ./run_fibonacci.sh

  #     - name: Sleep
  #       run: sleep 2400

  # job_23:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Run Fibonacci Task (Shell Script)
  #       run: |
  #         chmod +x run_fibonacci.sh
  #         ./run_fibonacci.sh

  #     - name: Sleep
  #       run: sleep 2400

  # job_24:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Run Fibonacci Task (Shell Script)
  #       run: |
  #         chmod +x run_fibonacci.sh
  #         ./run_fibonacci.sh

  #     - name: Sleep
  #       run: sleep 2400
  
  # job_5:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Print job name
  #       run: echo "job_5"
  #     - name: Sleep
  #       run: sleep 20

  # job_6:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Print job name
  #       run: echo "job_6"
  #     - name: Sleep
  #       run: sleep 20

  # job_7:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Print job name
  #       run: echo "job_7"
  #     - name: Sleep
  #       run: sleep 20

  # job_8:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Print job name
  #       run: echo "job_8"
  #     - name: Sleep
  #       run: sleep 20

  # job_9:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Print job name
  #       run: echo "job_9"
  #     - name: Sleep
  #       run: sleep 20

  # job_10:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Print job name
  #       run: echo "job_10"
  #     - name: Sleep
  #       run: sleep 20

  # job_11:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Print job name
  #       run: echo "job_11"
  #     - name: Sleep
  #       run: sleep 20

  # job_12:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Print job name
  #       run: echo "job_12"
  #     - name: Sleep
  #       run: sleep 20

  # job_13:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Print job name
  #       run: echo "job_13"
  #     - name: Sleep
  #       run: sleep 20

  # job_14:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Print job name
  #       run: echo "job_14"
  #     - name: Sleep
  #       run: sleep 20

  # job_15:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Print job name
  #       run: echo "job_15"
  #     - name: Sleep
  #       run: sleep 20

  # job_16:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Print job name
  #       run: echo "job_16"
  #     - name: Sleep
  #       run: sleep 20

  # job_17:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Print job name
  #       run: echo "job_17"
  #     - name: Sleep
  #       run: sleep 20

  # job_18:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Print job name
  #       run: echo "job_18"
  #     - name: Sleep
  #       run: sleep 20

  # job_19:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Print job name
  #       run: echo "job_19"
  #     - name: Sleep
  #       run: sleep 20

  # job_20:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Print job name
  #       run: echo "job_20"
  #     - name: Sleep
  #       run: sleep 20

  # job_21:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Print job name
  #       run: echo "job_21"
  #     - name: Sleep
  #       run: sleep 20

  # job_22:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Print job name
  #       run: echo "job_22"
  #     - name: Sleep
  #       run: sleep 20

  # job_23:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Print job name
  #       run: echo "job_23"
  #     - name: Sleep
  #       run: sleep 20

  # job_24:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Print job name
  #       run: echo "job_24"
  #     - name: Sleep
  #       run: sleep 20

  # job_25:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Print job name
  #       run: echo "job_25"
  #     - name: Sleep
  #       run: sleep 20
  
  # Explore-GitHub-Actions:
  #   runs-on: arc-runner-set
  #   steps:                    
  #     - name: Print job ID
  #       run: echo "jobs_10"
        
  #     - name: sleep1
  #       run: sleep 60

  # job_1:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Print job name
  #       run: echo "job_1"
  #     - name: Sleep
  #       run: sleep 20

  # job_2:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Print job name
  #       run: echo "job_2"
  #     - name: Sleep
  #       run: sleep 20

  # job_3:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Print job name
  #       run: echo "job_3"
  #     - name: Sleep
  #       run: sleep 20

  # job_4:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Print job name
  #       run: echo "job_4"
  #     - name: Sleep
  #       run: sleep 20

  # job_5:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Print job name
  #       run: echo "job_5"
  #     - name: Sleep
  #       run: sleep 20

  # job_6:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Print job name
  #       run: echo "job_6"
  #     - name: Sleep
  #       run: sleep 20

  # job_7:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Print job name
  #       run: echo "job_7"
  #     - name: Sleep
  #       run: sleep 20

  # job_8:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Print job name
  #       run: echo "job_8"
  #     - name: Sleep
  #       run: sleep 20

  # job_9:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Print job name
  #       run: echo "job_9"
  #     - name: Sleep
  #       run: sleep 20

  # job_10:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Print job name
  #       run: echo "job_10"
  #     - name: Sleep
  #       run: sleep 20

  # job_11:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Print job name
  #       run: echo "job_11"
  #     - name: Sleep
  #       run: sleep 20

  # job_12:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Print job name
  #       run: echo "job_12"
  #     - name: Sleep
  #       run: sleep 20

  # job_13:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Print job name
  #       run: echo "job_13"
  #     - name: Sleep
  #       run: sleep 20

  # job_14:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Print job name
  #       run: echo "job_14"
  #     - name: Sleep
  #       run: sleep 20

  # job_15:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Print job name
  #       run: echo "job_15"
  #     - name: Sleep
  #       run: sleep 20

  # job_16:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Print job name
  #       run: echo "job_16"
  #     - name: Sleep
  #       run: sleep 20

  # job_17:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Print job name
  #       run: echo "job_17"
  #     - name: Sleep
  #       run: sleep 20

  # job_18:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Print job name
  #       run: echo "job_18"
  #     - name: Sleep
  #       run: sleep 20

  # job_19:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Print job name
  #       run: echo "job_19"
  #     - name: Sleep
  #       run: sleep 20

  # job_20:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Print job name
  #       run: echo "job_20"
  #     - name: Sleep
  #       run: sleep 20

  # job_21:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Print job name
  #       run: echo "job_21"
  #     - name: Sleep
  #       run: sleep 20

  # job_22:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Print job name
  #       run: echo "job_22"
  #     - name: Sleep
  #       run: sleep 20

  # job_23:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Print job name
  #       run: echo "job_23"
  #     - name: Sleep
  #       run: sleep 20

  # job_24:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Print job name
  #       run: echo "job_24"
  #     - name: Sleep
  #       run: sleep 20

  # job_25:
  #   runs-on: arc-runner-set
  #   steps:
  #     - name: Print job name
  #       run: echo "job_25"
  #     - name: Sleep
  #       run: sleep 20
